# Use root/example as user/password credentials
version: "3.4"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data_volume:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: "false"

  fastapi-dev:
    build: .
    ports:
      - "8000:8000"
    environment:
      MONGODB_URI: mongodb://root:example@mongo:27017
      DEPLOYMENT: LOCAL
      UCI_SSO_ENABLED: "true"
    depends_on:
    - mongo

volumes:
  mongodb_data_volume:
    name: vh_mongodb_data
